version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myblog
    networks:
      springboot-blog-rest-api-mysql:

  springboot-blog-rest-api:
    container_name: springboot-blog-rest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-blog-rest-api-mysql:
    restart: on-failure

networks:
  springboot-blog-rest-api-mysql:
